# Generated by Django 3.2 on 2022-06-30 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('rayon', models.CharField(choices=[('FL', 'Fruits et Légumes'), ('V', 'Viande'), ('P', 'Poisson'), ('P1', 'Pain et Patisseries'), ('F', 'Frai'), ('S', 'Surgelé'), ('B', 'Boisson'), ('SA', 'Epicerie salée'), ('SU', 'Epicerie sucrée')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ListeIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.FloatField()),
                ('unite', models.CharField(choices=[('g', 'grammes'), ('p', 'pièces')], max_length=50)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recette.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('source', models.CharField(max_length=200)),
                ('nombre', models.IntegerField()),
                ('categorie', models.CharField(choices=[('Entrée', 'Entrée'), ('Plat', 'Plat'), ('Dessert', 'Dessert')], max_length=100)),
                ('description', models.TextField()),
                ('ingredients', models.ManyToManyField(through='recette.ListeIngredients', to='recette.Ingredient')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.source')),
            ],
        ),
        migrations.AddField(
            model_name='listeingredients',
            name='recette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recette.recette'),
        ),
    ]
