# Generated by Django 3.2 on 2022-07-02 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0002_auto_20220702_0808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='name',
            new_name='nom',
        ),
    ]
