# Generated by Django 3.2 on 2022-07-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0004_auto_20220702_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeingredients',
            name='unite',
            field=models.CharField(choices=[('g', 'grammes'), ('p', 'pièces'), ('cl', 'cl'), ('cas', 'CaS'), ('cac', 'CaC'), ('b', 'bottes')], max_length=50),
        ),
    ]
