# Generated by Django 3.2 on 2022-07-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0005_alter_listeingredients_unite'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='placard',
            field=models.BooleanField(default=False, verbose_name='Produit du placard'),
        ),
    ]
