# Generated by Django 3.2 on 2022-07-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0006_ingredient_placard'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='image',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='listeingredients',
            name='unite',
            field=models.CharField(choices=[('g', 'grammes'), ('p', 'pièces'), ('cl', 'cl'), ('cas', 'CaS'), ('cac', 'CaC'), ('b', 'bottes'), ('v', 'verres')], max_length=50),
        ),
    ]
