# Generated by Django 3.2 on 2022-07-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0007_auto_20220713_0746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('nom',)},
        ),
        migrations.AlterModelOptions(
            name='recette',
            options={'ordering': ('nom',)},
        ),
        migrations.AlterField(
            model_name='batch',
            name='nom',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='nom',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='recette',
            name='nom',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
