# Generated by Django 3.2 on 2022-11-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0008_auto_20220721_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='bio',
            field=models.BooleanField(default=False, verbose_name='Produit Bio'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='rayon',
            field=models.CharField(choices=[('FL', 'Fruits et Légumes'), ('V', 'Viande'), ('P', 'Poisson'), ('P1', 'Pain et Patisseries'), ('F', 'Frais'), ('S', 'Surgelé'), ('B', 'Boisson'), ('SA', 'Epicerie salée'), ('SU', 'Epicerie sucrée')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listeingredients',
            name='unite',
            field=models.CharField(choices=[('g', 'grammes'), ('u', 'unités'), ('p', 'pièces'), ('cl', 'cl'), ('cas', 'CaS'), ('cac', 'CaC'), ('b', 'bottes'), ('v', 'verres')], max_length=50),
        ),
    ]
