# Generated by Django 3.2 on 2022-11-20 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0009_auto_20221119_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recette',
            name='batch',
        ),
        migrations.AddField(
            model_name='batch',
            name='jour',
            field=models.CharField(choices=[('lundi', 'lundi'), ('mardi', 'mardi'), ('mercredi', 'mercredi'), ('jeudi', 'jeudi'), ('vendredi', 'vendredi')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='recette',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recette.recette'),
            preserve_default=False,
        ),
    ]
