# Generated by Django 3.2 on 2022-11-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0010_auto_20221120_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='categorie',
            field=models.CharField(choices=[('Entrée', 'Entrée'), ('Plat', 'Plat'), ('Dessert', 'Dessert'), ('Batch', 'Batch')], max_length=100),
        ),
    ]
