# Generated by Django 3.2 on 2024-11-11 13:44

from django.db import migrations, models

def migrate_categories(apps, schema_editor):
    Recette = apps.get_model('recette','recette')
    Categorie = apps.get_model('recette','categorie')
    
    Categorie.objects.create(nom='Entrée')
    Categorie.objects.create(nom='Plat')
    Categorie.objects.create(nom='Plat du weekend')
    Categorie.objects.create(nom='Plat végé')
    Categorie.objects.create(nom='Dessert')
    Categorie.objects.create(nom='Batch')
    
    for r in Recette.objects.all() :
        c = Categorie.objects.get(nom=r.categorie)
        r.categories.add(c)

class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0011_alter_recette_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='recette',
            name='is_batch',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listeingredients',
            name='unite',
            field=models.CharField(choices=[('g', 'grammes'), ('u', 'unités'), ('p', 'pièces'), ('cl', 'cl'), ('cas', 'CaS'), ('cac', 'CaC'), ('b', 'bottes'), ('v', 'verres'), ('cm', 'centimètres'), ('tr', 'tranches')], max_length=50),
        ),
        migrations.AlterField(
            model_name='recette',
            name='categorie',
            field=models.CharField(choices=[(None, '---------'), ('Entrée', 'Entrée'), ('Plat', 'Plat'), ('Plat du weekend', 'Plat du weekend'), ('Plat végé', 'Plat végé'), ('Dessert', 'Dessert'), ('Batch', 'Batch')], max_length=100),
        ),
        migrations.AddField(
            model_name='recette',
            name='categories',
            field=models.ManyToManyField(to='recette.Categorie'),
        ),
        migrations.RunPython(migrate_categories)
    ]
