# Generated by Django 3.2 on 2022-07-11 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recette', '0006_ingredient_placard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portions', models.IntegerField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menu')),
                ('recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recette.recette')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='recettes',
            field=models.ManyToManyField(through='menu.MenuComposition', to='recette.Recette'),
        ),
    ]
