# Generated by Django 3.2 on 2022-07-21 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='date_fin',
            field=models.DateField(default=datetime.date(2022, 7, 29)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='date',
            field=models.DateField(),
        ),
    ]
