# Generated by Django 3.2 on 2022-07-02 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='name',
            new_name='nom',
        ),
    ]
